{% set version = "8.18.1" %}

{% set migrating = false %}

package:
  name: ipython
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipython/ipython-{{ version }}.tar.gz
  sha256: ca6f079bb33457c66e233e4580ebfc4128855b4cf6370dddd73842a9563e8a27

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

  noarch: python
  script_env:
    - MIGRATING={{ migrating }}
    - COV_THRESHOLD=71  # [unix]
    - COV_THRESHOLD=70  # [win]
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=51.0.0
  run:
    - __unix          # [unix]
    - __win           # [win]
    - python >=3.9
    - colorama        # [win]
    - decorator
    - exceptiongroup
    - jedi >=0.16
    - matplotlib-inline
    - pexpect >4.3    # [unix]
    - pickleshare
    - prompt-toolkit >=3.0.41,<3.1.0
    - pygments >=2.4.0
    - stack_data
    - traitlets >=5
    - typing_extensions

test:
  source_files:
    - pyproject.toml
  requires:
    - pip
    - m2-grep  # [win]
    {% if not migrating %}
    - black
    - curio
    - matplotlib-base !=3.2.0
    - nbformat
    - numpy >=1.21
    - pandas
    - pickleshare
    - pygments
    - pytest <7.1
    - pytest-asyncio <0.22
    - pytest-cov
    - testpath
    - trio
    # mypy
    - mypy
    - types-decorator
    {% endif %}

  imports:
    - IPython
    - IPython.core
    - IPython.core.magics
    - IPython.core.tests
    - IPython.extensions
    - IPython.extensions.tests
    - IPython.external
    - IPython.lib
    - IPython.lib.tests
    - IPython.sphinxext
    - IPython.terminal
    - IPython.terminal.pt_inputhooks
    - IPython.terminal.tests
    - IPython.testing
    - IPython.testing.plugin
    - IPython.testing.tests
    - IPython.utils
    - IPython.utils.tests
  commands:
    - pip check
    - pygmentize -L | grep ipython
    - ipython -h
    - ipython3 -h
    {% if not migrating %}
    - mypy -p IPython || exit 0
    {% endif %}

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.
  doc_url: https://ipython.readthedocs.io
  dev_url: https://github.com/ipython/ipython

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - fperez
    - ellisonbg
    - minrk
    - ocefpaf
    - pelson
    - takluyver
    - bollwyvl
    - blink1073
