{% set version = "6.5.0" %}

package:
  name: ipython
  version: {{ version }}

source:
  fn: ipython-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipython/ipython-{{ version }}.tar.gz
  sha256: b0f2ef9eada4a68ef63ee10b6dde4f35c840035c50fd24265f8052c98947d5a4

build:
  number: 0
  script: python -m pip install --no-deps .
  skip: True  # [py2k]
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython  # [py3k]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pickleshare
    - simplegeneric >0.8
    - prompt_toolkit >=1.0.4,<2.0.0
    - pygments
    - decorator
    - traitlets >=4.2
    - jedi >=0.10
    - pexpect  # [unix]
    - appnope  # [osx]
    - colorama  # [win]
    - win_unicode_console >=0.5  # [win and py<36]
    - backcall

test:
  commands:
    - ipython -h
    - ipython3 -h          # [py3k]
  imports:
    - IPython

about:
  home: https://ipython.org/
  license: BSD 3-clause
  license_file: COPYING.rst
  summary: "IPython: Productive Interactive Computing"

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - takluyver
