{% set version = "4.2.0" %}

package:
  name: ipython
  version: {{ version }}

source:
  fn: ipython-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/4e/c7/519b95112dba6f3ae91530bcb8564454c575fcb1fdb323b2b0ee9eff1227/ipython-{{ version }}.tar.gz
  md5: 9c7c28eddbc39eb874d2c22025772d63

build:
  script: python -m pip install --no-deps .
  number: 2
  entry_points:
    - ipython = IPython:start_ipython
    - ipython2 = IPython:start_ipython  # [py2k]
    - ipython3 = IPython:start_ipython  # [py3k]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pickleshare
    - python-simplegeneric >0.8
# These are listed in the setup.py, but do not cause the build tests to fail.
# In order to enable these dependencies, additional tests will need to be defined.
#    - prompt_toolkit >=0.60
#    - pygments
    - python-decorator
    - traitlets
    - pexpect              # [unix]
    - appnope              # [osx]
    - pyreadline           # [win]
    - backports.shutil_get_terminal_size
    - python.app           # [osx]

test:
  commands:
    - ipython -h
    - ipython2 -h          # [py2k]
    - ipython3 -h          # [py3k]
  imports:
    - IPython

about:
  home: http://ipython.org/
  license: BSD 3-clause
  summary: "IPython: Productive Interactive Computing"

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
