{% set version = "7.16.0" %}

package:
  name: ipython
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipython/ipython-{{ version }}.tar.gz
  sha256: 075e90eee2501c7ecd5fbccb91659c6658e3619231b93150b5f2eadfd6b81615

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython
    - iptest = IPython.testing.iptestcontroller:main
    - iptest3 = IPython.testing.iptestcontroller:main

requirements:
  host:
    - pip
    - python
  run:
    - appnope  # [osx]
    - backcall
    - colorama  # [win]
    - decorator
    - jedi >=0.10
    - pexpect  # [unix]
    - pickleshare
    - prompt-toolkit !=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
    - pygments
    - python
    - traitlets >=4.2
    - setuptools >=18.5

# generally failing
{% set nose_exclude = "recursion" %}
{% set nose_exclude = nose_exclude ~ "|test_history" %}  # [not win]
# https://github.com/ipython/ipython/issues/12164
{% set nose_exclude = nose_exclude ~ "|system_interrupt" %}  # [linux]
{% set nose_exclude = nose_exclude ~ "|home_dir_3|home_dir_5|store_restore|storemagic" %}  # [win]

test:
  requires:
    # TODO: restore after pypy migration
    # - curio  # [unix]
    # - ipykernel
    # - matplotlib
    # - nbformat
    # - nose >=0.10.1
    # - numpy
    # - pygments
    # - requests
    # - testpath
    # - trio
    - pip
  imports:
    - IPython
    - IPython.core
    - IPython.core.magics
    - IPython.core.tests
    - IPython.extensions
    - IPython.extensions.tests
    - IPython.external
    - IPython.external.decorators
    - IPython.lib
    - IPython.lib.tests
    - IPython.sphinxext
    - IPython.terminal
    - IPython.terminal.pt_inputhooks
    - IPython.terminal.tests
    - IPython.testing
    - IPython.testing.plugin
    - IPython.testing.tests
    - IPython.utils
    - IPython.utils.tests
  commands:
    - ipython -h
    - ipython3 -h
    # TODO: restore after pypy migration
    # - NOSE_EXCLUDE="{{ nose_exclude }}" iptest  # [unix]
    # - set NOSE_EXCLUDE="{{ nose_exclude }}" && iptest  # [win]
    - python -m pip check

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.
  doc_url: https://ipython.readthedocs.io
  dev_url: https://github.com/ipython/ipython

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - fperez
    - ellisonbg
    - minrk
    - ocefpaf
    - pelson
    - takluyver
    - bollwyvl
    - blink1073
