{% set version = "8.12.0" %}

{% set migrating = false %}

package:
  name: ipython
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipython/ipython-{{ version }}.tar.gz
  sha256: a950236df04ad75b5bc7f816f9af3d74dc118fd42f2ff7e80e8e60ca1f182e2d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

  noarch: python
  script_env:
    - MIGRATING={{ migrating }}
    # TODO: investigate removing when some pypy/coverage speed issues are resolved
    - IPYTHON_TESTING_TIMEOUT_SCALE=10
    - COV_THRESHOLD=73  # [unix]
    - COV_THRESHOLD=72  # [win]
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - __{{ noarch_platform }}
    - python >=3.8
    {% if noarch_platform == "osx" %}
    - appnope
    {% endif %}
    - backcall
    {% if noarch_platform == "win" %}
    - colorama
    {% endif %}
    - decorator
    - jedi >=0.16
    - matplotlib-inline
    {% if noarch_platform != "win" %}
    - pexpect >4.3
    {% endif %}
    - pickleshare
    - prompt_toolkit >=3.0.30,<3.1.0,!=3.0.37
    - pygments >=2.4.0
    - stack_data
    - traitlets >=5

test:
  requires:
    - pip
    - m2-grep  # [win]
    {% if not migrating %}
    - black
    - curio
    - matplotlib-base !=3.2.0
    - nbformat
    - numpy >=1.21
    - pandas
    - pygments
    - pytest <7
    - pytest-cov
    - testpath
    - trio
    {% endif %}

  imports:
    - IPython
    - IPython.core
    - IPython.core.magics
    - IPython.core.tests
    - IPython.extensions
    - IPython.extensions.tests
    - IPython.external
    - IPython.lib
    - IPython.lib.tests
    - IPython.sphinxext
    - IPython.terminal
    - IPython.terminal.pt_inputhooks
    - IPython.terminal.tests
    - IPython.testing
    - IPython.testing.plugin
    - IPython.testing.tests
    - IPython.utils
    - IPython.utils.tests
  commands:
    - pip check
    - pygmentize -L | grep ipython
    - ipython -h
    - ipython3 -h

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.
  doc_url: https://ipython.readthedocs.io
  dev_url: https://github.com/ipython/ipython

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - fperez
    - ellisonbg
    - minrk
    - ocefpaf
    - pelson
    - takluyver
    - bollwyvl
    - blink1073
