{% set version = "5.8.0" %}

package:
  name: ipython
  version: {{ version }}

source:
  fn: ipython-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipython/ipython-{{ version }}.tar.gz
  sha256: 4bac649857611baaaf76bc82c173aa542f7486446c335fe1a6c05d0d491c8906

build:
  number: 1
  script: python -m pip install --no-deps .
  entry_points:
    - ipython = IPython:start_ipython
    - ipython2 = IPython:start_ipython  # [py2k]
    - ipython3 = IPython:start_ipython  # [py3k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pickleshare
    - simplegeneric >0.8
    - prompt_toolkit >=1.0.4,<2.0.0
    - pygments
    - decorator
    - traitlets
    - pexpect  # [unix]
    - backports.shutil_get_terminal_size  # [py2k]
    - pathlib2  # [py2k]
    - appnope  # [osx]
    - colorama  # [win]
    - win_unicode_console >=0.5  # [win and py<36]

test:
  commands:
    - ipython -h
    - ipython2 -h          # [py2k]
    - ipython3 -h          # [py3k]
  imports:
    - IPython

about:
  home: https://ipython.org/
  license: BSD 3-clause
  license_file: COPYING.rst
  summary: "IPython: Productive Interactive Computing"
  home: https://ipython.org/
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.
  doc_url: https://ipython.readthedocs.io/
  dev_url: https://github.com/ipython/ipython

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - takluyver
