{% set version = "8.30.0" %}

{% set python_min = python_min | default("3.10") %}

package:
  name: ipython
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/ipython/ipython-{{ version }}.tar.gz
  sha256: cb0a405a306d2995a5cbb9901894d240784a9f341394c6ba3f4fe8c6eb89ff6e

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

  noarch: python
  script_env:
    - COV_THRESHOLD=71  # [unix]
    - COV_THRESHOLD=70  # [win]
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.2
  run:
    - __unix          # [unix]
    - __win           # [win]
    - colorama        # [win]
    - python >={{ python_min }}
    - decorator
    - exceptiongroup
    - jedi >=0.16
    - matplotlib-inline
    - pexpect >4.3    # [unix]
    - pickleshare
    - prompt-toolkit >=3.0.41,<3.1.0
    - pygments >=2.4.0
    - stack_data
    - traitlets >=5.13.0
    - typing_extensions >=4.6

test:
  source_files:
    - pyproject.toml
  requires:
    # pip check
    - pip
    # CFEP-25 minimum python
    - python {{ python_min }}
    # mypy
    - mypy
    - types-decorator
    # windows
    - m2-grep  # [win]
    # actual test deps
    - black
    - curio
    - matplotlib-base !=3.2.0
    - nbformat
    - numpy >=1.23
    - pandas
    - pickleshare
    - pygments
    - pytest
    - pytest-asyncio <0.22
    - pytest-cov
    - testpath
    - trio

  imports:
    - IPython
    - IPython.core
    - IPython.core.magics
    - IPython.core.tests
    - IPython.extensions
    - IPython.extensions.tests
    - IPython.external
    - IPython.lib
    - IPython.lib.tests
    - IPython.sphinxext
    - IPython.terminal
    - IPython.terminal.pt_inputhooks
    - IPython.terminal.tests
    - IPython.testing
    - IPython.testing.plugin
    - IPython.testing.tests
    - IPython.utils
    - IPython.utils.tests
  commands:
    - pip check
    - pygmentize -L | grep ipython
    - ipython -h
    - ipython3 -h
    - mypy -p IPython || exit 0

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.
  doc_url: https://ipython.readthedocs.io
  dev_url: https://github.com/ipython/ipython

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - fperez
    - ellisonbg
    - minrk
    - ocefpaf
    - pelson
    - takluyver
    - bollwyvl
    - blink1073
