# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 8.32.0

package:
  name: ipython
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/ipython/ipython-${{ version }}.tar.gz
  sha256: be2c91895b0b9ea7ba49d33b23e2040c352b33eb6a519cca7ce6e0c743444251

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - ipython = IPython:start_ipython
      - ipython3 = IPython:start_ipython

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61.2
  run:
    - if: unix
      then:
        - __unix
        - pexpect >4.3
      else:
        - __win
        - colorama
    - python >=${{ python_min }}
    - decorator
    - exceptiongroup
    - jedi >=0.16
    - matplotlib-inline
    - pickleshare
    - prompt-toolkit >=3.0.41,<3.1.0
    - pygments >=2.4.0
    - stack_data
    - traitlets >=5.13.0
    - typing_extensions >=4.6

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports:
        - IPython
        - IPython.core
        - IPython.core.magics
        - IPython.core.tests
        - IPython.extensions
        - IPython.extensions.tests
        - IPython.external
        - IPython.lib
        - IPython.lib.tests
        - IPython.sphinxext
        - IPython.terminal
        - IPython.terminal.pt_inputhooks
        - IPython.terminal.tests
        - IPython.testing
        - IPython.testing.plugin
        - IPython.testing.tests
        - IPython.utils
        - IPython.utils.tests
  - files:
      recipe:
        - run_test.py
      source:
        - pyproject.toml
    requirements:
      run:
        # repeat pip check on unconstrained python
        - pip
        # mypy
        - mypy
        - types-decorator
        # windows
        # actual test deps
        - black
        - curio
        - matplotlib-base !=3.2.0
        - nbformat
        - numpy >=1.23
        - pandas
        - pickleshare
        - pygments
        - pytest
        - pytest-asyncio <0.22
        - pytest-cov
        - testpath
        - trio
        - if: win
          then:
            - m2-grep
    script:
      - pip check
      - pygmentize -L | grep ipython
      - ipython -h
      - ipython3 -h
      - mypy -p IPython || exit 0
      - python run_test.py

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
  homepage: https://ipython.org
  documentation: https://ipython.readthedocs.io
  repository: https://github.com/ipython/ipython
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - fperez
    - ellisonbg
    - minrk
    - ocefpaf
    - pelson
    - takluyver
    - bollwyvl
    - blink1073
    - krassowski
    - trallard
