# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "9.7.0"
  python_check_max: "3.14"

recipe:
  name: ipython
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/ipython/ipython-${{ version }}.tar.gz
  sha256: 5f6de88c905a566c6a9d6c400a8fed54a638e1f7543d17aae2551133216b1e4e

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: ipython
    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      python:
        entry_points:
          - ipython = IPython:start_ipython
          - ipython3 = IPython:start_ipython
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools >=77.0
      run:
        - __${{ noarch_platform }}
        - ${{ "colorama >=0.4.4" if noarch_platform == "win" else "pexpect >4.3" }}
        - decorator >=4.3.2
        - ipython_pygments_lexers >=1.0.0
        - jedi >=0.18.1
        - matplotlib-inline >=0.1.5
        - prompt-toolkit >=3.0.41,<3.1.0
        - pygments >=2.11.0
        - python >=${{ python_min }}
        - stack_data >=0.6.0
        - traitlets >=5.13.0
        - typing_extensions >=4.6
    tests:
      - python:
          imports: IPython
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - ipython --version
          - ipython3 --version
          - ipython --help
          - pygmentize -L | python -c "import sys; assert 'ipython' in sys.stdin.read()"
      # TODO: unvendor tests as separate package
      - files:
          recipe:
            - run_test.py
          source:
            - tests/
            - pyproject.toml
        requirements:
          run:
            - python ${{ python_min }}.*
            # mypy
            - mypy
            - types-decorator
            # coverage
            - coverage
            # actual test deps
            - black
            - curio
            - ipykernel >6.30
            - matplotlib-base >=3.9
            - nbformat
            - numpy >=1.27
            - packaging >=20.1.0
            - pandas >=2.1
            - pytest >=7.0.0
            - pytest-asyncio >=1.0.0
            - setuptools >=61.2
            - testpath >=0.2
            - trio >=0.1.0
        script:
          - if: unix
            then:
              # win fails with e.g. _process_win32.py:172: error: "_NamedFuncPointer" has no attribute "arg_types"  [attr-defined]
              - mypy -p IPython
          - python run_test.py

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
  homepage: https://ipython.org
  documentation: https://ipython.readthedocs.io
  repository: https://github.com/ipython/ipython
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.

extra:
  feedstock-name: ipython
  recipe-maintainers:
    - Carreau
    - jakirkham
    - fperez
    - ellisonbg
    - minrk
    - ocefpaf
    - pelson
    - takluyver
    - bollwyvl
    - blink1073
    - krassowski
    - trallard
