travis:
  secure:
    BINSTAR_TOKEN: LtyspOyo5PerS2x7IIBODJmdAvxeEHFsfSyviq9xQJZ7LHeVK/vDR7Oed0RarvzZrs3tcM/PKRG9fhCQRL9sjvEAfCWAE+35R627fbUJf1LvZzqb3t5JU+fwC5ycYSSYb/VFHq86e8Pqy4D75JRE2xhHPeqy8hnTNTBq0+AwGL1r/E2FEmgSK25+xlwjciXc2X3VAUR0rqz4fzsLly11+q4Yi7MrTF7O/vHOVd03k3gSsXoANIRgMMJaKsnkDofeixnQzjtpV7jMQedlwtt5j3N6lmjfk6zBJ9Oo38exinMeH4Zrx3m+czW74D4uJgnbDTxc/Csr3a8VV1m1ZS/rP/4JGVq8AYV5cM02MaeZDsftU9J1H6/sAs2B9i17iRV+mPc2fcXdFGbYalwH2a1Qab3+skYpa+ECOEpYqxvVnu+6K1oMSC9IWX1jHVEJb6tM11O3sV7pxzYdiWQyquodrOkXadXunZkaWx7B+gefQI5/JM4gY7DhtKWFaoXXhN8OQheU8ati47kVssTSXil+0KPecINnSFgvH6ny3dVKii9ncJHRlyZeoKAYx1k+2PGkRXWQlcmSQngiL30nVRjb+7UZRlRHqfyiHVRtJ53JEHOtI9KTau6ki2M0ya2sOLNZv8qeXMPeRNLtFOlZDd/8BtY772Rlu9X34wVKYUni0/8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
