build_platform: {osx_arm64: osx_64}
appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: vJ/JWZF6J7xMvDV0qL4RRvY+AEavBfkJSlh4SEgwuJLKX70ne0rDysTUNs3VWOB34q9COoPUsqaAXG3mBTCwQigcGEPF6f4zLTUMI8UhkRmhpYTJol0j2NBSDI9yEHmKkev/HiQnNM/MPtVpZpwZxSioJDr56brGDUhTiFw5+4RkoUN61MwzLB82VAjdyRN8Dc51HYKQBOUgQ2Y4BehiN1W8NiDLdDkYmei/yh3Xiqa1VS806BYsLHqAKu3FpJkDg1fpGk2IB5txCEMSR8xi7miPOAOFvA+TuwVNXtcZXZa7hY5cn+BhZlg418XUNHsSmd/uO/ZGQIkr8LhacOhe4u2uameB68nGq79GUbQsoZUXWI5hfJnFxP6B11wLvQ1XDz2D8iAcYislPVbQah/4Q2Uf7jjnjkbQqVhU4Ov03hVAmut5zA3YtWxbZONMxmmpe0TWJtbSRUA+OPRmssNym3Ocd19PSzC4rJrHQIQv4Ln990XZs4L0VGd4w/OA+ND00yP9TsuqNglWO+JvpMoXErUygld3JQEolq560A0085nRnQzNuhyg3TnKVofKBRd9WfT8VMZ2v+rNBbHYqrnJG/MxBzFM4WirfrTK88922aNkQAByf6zXhekU3hW8ZunNxSyBJyELvOOoJ/5hbELBp4w08Dtn34VnAnVbPGR2YpM=}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
test_on_native_only: true
